# cloudbuild.yaml

substitutions:
  _CLUSTER: "airflow-dev-cluster"
  _ZONE:    "europe-west1-b"


options:
  # Option A: GCP сам создаст бакет в регионе
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  # Или, вместо этого, явно указать свой бакет:
  # logsBucket: "gs://my-project-build-logs"
  # Либо задать режим логирования:
  # logging: CLOUD_LOGGING_ONLY   # (по умолчанию)
  # logging: NONE                 # если не нужны логи в GCS

steps:
  # 0. Включить API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'enable-apis'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud services enable container.googleapis.com \
                                compute.googleapis.com \
                                iam.googleapis.com \
                                compute.googleapis.com \
                                --project=${PROJECT_ID}

  # 0.1 Зарезервировать глобальный статический IP (если ещё нет)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'reserve-ip'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud compute addresses describe airflow-ip --global >/dev/null 2>&1; then
          echo "Резервируем статический IP airflow-ip..."
          gcloud compute addresses create airflow-ip --global --project=${PROJECT_ID}
        else
          echo "IP airflow-ip уже зарезервирован."
        fi

  # 1. Создать кластер (если нужно)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-cluster'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLUSTER=airflow-cluster; Z=europe-west1-b
        if ! gcloud container clusters describe ${_CLUSTER} --zone=${_ZONE} >/dev/null 2>&1; then
          gcloud container clusters create ${_CLUSTER} \
            --zone ${_ZONE} \
            --machine-type e2-medium \
            --num-nodes 1 \
            --enable-ip-alias \
            --project=${PROJECT_ID}
        fi

  # 2. Получить креды для kubectl/helm
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'auth-gke'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER} \
          --zone=europe-west1-b \
          --project=${PROJECT_ID}

  # 3. Сборка Docker-образа Airflow
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/airflow:${SHORT_SHA}', '.']

  # 4. Пуш в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args: ['push', 'gcr.io/${PROJECT_ID}/airflow:${SHORT_SHA}']

  # 5. Деплой через Helm с Ingress
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'helm-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail

        # 1) Устанавливаем Helm 3
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        # 2) Убедимся, что плагин аутентификации для GKE на месте
        gcloud components install gke-gcloud-auth-plugin --quiet || true

        # 3) Получаем креды для kubectl/Helm
        gcloud container clusters get-credentials ${_CLUSTER} \
          --zone ${_ZONE} --project ${PROJECT_ID}

        # 4) Регистрируем репозиторий и обновляем чарты
        helm repo add apache-airflow https://airflow.apache.org || true
        helm repo update

        # 5) Запускаем сам деплой
        helm upgrade --install airflow apache-airflow/airflow \
          --namespace airflow --create-namespace \
          --set image.repository=gcr.io/${PROJECT_ID}/airflow \
          --set image.tag=${SHORT_SHA} \
          --set ingress.enabled=true \
          --set ingress.ingressClassName=gce \
          --set ingress.annotations."kubernetes\\.io/ingress\\.global-static-ip-name"=airflow-ip \
          --set ingress.annotations."networking\\.gke\\.io/managed-certificates"=airflow-cert \
          --set ingress.hosts[0].host=airflow.internal.domain.com \
          --set ingress.hosts[0].paths[0].path="/*" \
          --set ingress.hosts[0].paths[0].pathType=ImplementationSpecific

# Образы для реестра
images:
  - 'gcr.io/${PROJECT_ID}/airflow:${SHORT_SHA}'
